apiVersion: v1
kind: Service
metadata:
  name: kc-postgres
  namespace: kube-social
  labels: 
    app: postgres
    definedto: keycloack
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-postgres
  namespace: kube-social
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata: 
      labels: 
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        envFrom:
          - secretRef:
              name: kc-postgres-credentials
        ports:
        - containerPort: 5432
          name: kc-postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources: 
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: kc-postgres-pvc
      